apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlassian.fullname" . }}-config
  labels:
    {{- include "atlassian.labels" . | nindent 4 }}
data:
  {{- if .Values.config.confluenceURL }}
  CONFLUENCE_URL: {{ .Values.config.confluenceURL | quote }}
  {{- end }}
  {{- if .Values.config.jiraURL }}
  JIRA_URL: {{ .Values.config.jiraURL | quote }}
  {{- end }}
  {{- if .Values.config.confluenceSpacesFilter }}
  CONFLUENCE_SPACES_FILTER: {{ .Values.config.confluenceSpacesFilter | quote }}
  {{- end }}
  {{- if .Values.config.jiraProjectsFilter }}
  JIRA_PROJECTS_FILTER: {{ .Values.config.jiraProjectsFilter | quote }}
  {{- end }}
