apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlassian.fullname" . }}-secrets
  labels:
    {{- include "atlassian.labels" . | nindent 4 }}
type: Opaque
data:
  CONFLUENCE_USERNAME: {{ .Values.secrets.confluenceUsername | b64enc | quote }}
  CONFLUENCE_TOKEN: {{ .Values.secrets.confluenceToken | b64enc | quote }}
  JIRA_USERNAME: {{ .Values.secrets.jiraUsername | b64enc | quote }}
  JIRA_TOKEN: {{ .Values.secrets.jiraToken | b64enc | quote }}
